name: Build .exe

on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    types: [dispatch-event]

jobs:
  build:
    name: Build .exe
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Install Open Pectus Engine Manager
        run: pip install -e ".[development]"
      - name: Type check with pyright
        run: pyright
      - name: Test with unittest
        run: python -m unittest
      - name: Build .exe
        run: |
          pyinstaller pyinstaller.spec
          cd dist
          move "Open Pectus Engine Manager.exe" ../
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Open Pectus Engine Manager.exe"
          tag: release
          body: "Download and run `Open Pectus Engine Manager.exe`."
          allowUpdates: true
          makeLatest: true
          omitBodyDuringUpdate: true
          removeArtifacts: true
          replacesArtifacts: true
